name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
  MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: node tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: node . --help
